Algoritmo "ExercicioProcedimento"


procedimento multi

Var
   num: inteiro
inicio
      num <- pri * seg
      res <- num
fimProcedimento

var
   res, pri, seg: inteiro


Inicio

      Escreval("Informe o primeiro número: ")
      leia(pri)
      Escreval("Agora, informe o segundo número, para que possamos multiplicar: ")
      leia(seg)
      multi
          escreva ("O resultado da multiplicação é: ", res)


Fimalgoritmo