Algoritmo "Exercício3"

Var

   nomeAlgoritmo: caracter
   soma: inteiro
   resultadoMedia: real


Inicio

      nomeAlgoritmo <- "Exercício 3"
      soma <- 4+9+6+7+2
      resultadoMedia <- soma/5
      
      
      Escreval("Nome deste algoritmo: ", nomeAlgoritmo)
      Escreval("Números somados: 4+9+6+7+2")
      Escreval("Resultado da soma: ", soma)
      Escreval("Média da soma acima: ", resultadoMedia)


Fimalgoritmo